services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: project12-php84
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true
    name: mysql-network